[package]
name = "jeb_keygen_gui"
version = "1.0.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.0"
hex = "0.4.3"
chrono = "0.4.22"

[build-dependencies]
slint-build = "1.0"
